# Generated by Django 4.1.1 on 2022-09-16 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, default=0, null=True)),
                ('birth_place', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('adress', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('phone_number', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('room_number', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('bed_number', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('entry_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, default=0, null=True)),
                ('diagnostic', models.TextField(blank=True, default=0, null=True)),
                ('medical_history', models.TextField(blank=True, default=0, null=True)),
                ('body_exam', models.TextField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_treatment', models.TextField(blank=True, null=True)),
                ('general_treatment', models.TextField(blank=True, null=True)),
                ('progress_report', models.TextField(blank=True, null=True)),
                ('complementary_exam', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=30, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('proffesion', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.SmallIntegerField(blank=True, null=True)),
                ('room_number', models.SmallIntegerField(blank=True, null=True)),
                ('bed_number', models.SmallIntegerField(blank=True, null=True)),
                ('entry_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('body_exam', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
